import { PropertyUI } from "@/types/property";

export const MOCK_PROPERTIES: PropertyUI[] = [
  {
    id: "1",
    slug: "6br-alaya-villa-al-mouj",
    title: "6BR Alaya Villa",
    location: "Al Mouj Muscat, Muscat",
    city: "Muscat",
    community: "Al Mouj",
    price: 1406000,
    currency: "OMR",
    type: "Villa",
    status: "For Sale",
    bedrooms: 6,
    bathrooms: 5,
    area: 907.5,
    plotArea: 1005,
    description: "Welcome to a home where elegance meets everyday comfort. This stunning Alaya Villa in Al Mouj offers an unparalleled living experience with breathtaking waterfront views and world-class finishes.",
    images: ["/p1.jpg", "/p2.jpg", "/p3.jpg", "/p4.jpg", "/p5.jpg"],
    amenities: [
      { title: "Private Beach", icon: "Beach" },
      { title: "Infinity Pool", icon: "Waves" },
      { title: "Smart Home", icon: "Cpu" },
      { title: "Private Elevator", icon: "ArrowUpCircle" },
    ],
    paymentPlan: [{ percentage: "100%", condition: "Full Payment", timing: "At Closing" }],
    highlights: ["Freehold Ownership", "Foreign Investor Eligible", "Residency Benefits"],
    coordinates: { lat: 23.6139, lng: 58.5233 },
    featured: true,
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "2",
    slug: "sultan-haitham-penthouse",
    title: "Sultan Haitham Penthouse",
    location: "Sultan Haitham City, Muscat",
    city: "Muscat",
    community: "Sultan Haitham City",
    price: 850000,
    currency: "OMR",
    type: "Penthouse",
    status: "Off-plan",
    bedrooms: 4,
    bathrooms: 4,
    area: 450,
    description: "An architectural masterpiece in the heart of the most ambitious urban project in Oman.",
    images: ["/p2.jpg", "/p3.jpg", "/p1.jpg", "/p4.jpg"],
    amenities: [{ title: "Smart Systems", icon: "Zap" }, { title: "Central Air", icon: "Wind" }],
    paymentPlan: [{ percentage: "10%", condition: "Booking", timing: "Immediate" }],
    highlights: ["Sustainable City", "High ROI Potential"],
    coordinates: { lat: 23.5800, lng: 58.4500 },
    featured: true,
    createdAt: "2026-02-01T00:00:00Z",
  },
  {
    id: "3",
    slug: "bay-view-estate",
    title: "Bay View Estate",
    location: "Muscat Bay, Muscat",
    city: "Muscat",
    community: "Muscat Bay",
    price: 2100000,
    currency: "OMR",
    type: "Villa",
    status: "For Sale",
    bedrooms: 7,
    bathrooms: 6,
    area: 1200,
    plotArea: 1500,
    description: "A sanctuary of luxury nestled between the mountains and the turquoise waters of Muscat Bay.",
    images: ["/p3.jpg", "/p4.jpg", "/p1.jpg", "/p2.jpg"],
    amenities: [{ title: "Private Beach", icon: "Palmtree" }, { title: "Infinity Pool", icon: "Waves" }],
    paymentPlan: [{ percentage: "100%", condition: "Full Payment", timing: "At Closing" }],
    highlights: ["Freehold Ownership", "Beachfront Location"],
    coordinates: { lat: 23.4000, lng: 58.6000 },
    featured: true,
    createdAt: "2026-03-01T00:00:00Z",
  },
  {
    id: "4",
    slug: "sifah-cliff-house",
    title: "Sifah Cliff House",
    location: "Jebel Sifah, Muscat",
    city: "Muscat",
    community: "Jebel Sifah",
    price: 600000,
    currency: "OMR",
    type: "Villa",
    status: "Ready to Move",
    bedrooms: 3,
    bathrooms: 3,
    area: 350,
    description: "Experience the raw beauty of the Omani coast from this stunning cliffside residence.",
    images: ["/p4.jpg", "/p1.jpg", "/p2.jpg", "/p3.jpg"],
    amenities: [{ title: "Outdoor Firepit", icon: "Flame" }, { title: "Hiking Trails", icon: "Mountain" }],
    paymentPlan: [{ percentage: "20%", condition: "Down Payment", timing: "At Signing" }],
    highlights: ["Ready To Move", "Cliffside View"],
    coordinates: { lat: 23.2000, lng: 58.3000 },
    featured: false,
    createdAt: "2026-04-01T00:00:00Z",
  },
  {
    id: "5",
    slug: "qurum-luxury-apartment",
    title: "Qurum Luxury Apartment",
    location: "Qurum, Muscat",
    city: "Muscat",
    community: "Qurum",
    price: 450000,
    currency: "OMR",
    type: "Apartment",
    status: "For Sale",
    bedrooms: 3,
    bathrooms: 2,
    area: 220,
    description: "Sleek urban living in the most prestigious district of Muscat.",
    images: ["/p1.jpg", "/p2.jpg", "/p3.jpg"],
    amenities: [{ title: "Concierge", icon: "User" }, { title: "Gym", icon: "Dumbbell" }],
    paymentPlan: [{ percentage: "100%", condition: "Full Payment", timing: "At Closing" }],
    highlights: ["City Center", "High Demand"],
    coordinates: { lat: 23.6200, lng: 58.5400 },
    featured: true,
    createdAt: "2026-05-01T00:00:00Z",
  },
  {
    id: "6",
    slug: "aida-coastal-villa",
    title: "AIDA Coastal Villa",
    location: "Southern Coast, Oman",
    city: "Salalah",
    community: "AIDA",
    price: 320000,
    currency: "OMR",
    type: "Villa",
    status: "Under Construction",
    bedrooms: 4,
    bathrooms: 4,
    area: 400,
    description: "Visionary design meets coastal sophistication in the heart of AIDA.",
    images: ["/p1.jpg", "/p2.jpg", "/p3.jpg", "/p4.jpg"],
    amenities: [{ title: "Beach Access", icon: "Beach" }, { title: "Wellness Hub", icon: "Heart" }],
    paymentPlan: [{ percentage: "20%", condition: "Booking", timing: "Immediate" }],
    highlights: ["First-Mover Advantage", "Coastal View"],
    coordinates: { lat: 17.2400, lng: 54.0900 },
    featured: true,
    createdAt: "2026-06-01T00:00:00Z",
  },
  {
    id: "7",
    slug: "la-mer-penthouse",
    title: "La Mer Penthouse",
    location: "Al Mouj Muscat, Muscat",
    city: "Muscat",
    community: "Al Mouj",
    price: 980000,
    currency: "OMR",
    type: "Penthouse",
    status: "Ready to Move",
    bedrooms: 3,
    bathrooms: 3,
    area: 300,
    description: "Breathtaking waterfront penthouse with expansive terraces.",
    images: ["/p3.jpg", "/p4.jpg", "/p1.jpg"],
    amenities: [{ title: "Marina Views", icon: "Ship" }, { title: "Private Lift", icon: "ArrowUp" }],
    paymentPlan: [{ percentage: "100%", condition: "Full Payment", timing: "At Closing" }],
    highlights: ["Waterfront", "Ready to Move"],
    coordinates: { lat: 23.6140, lng: 58.5240 },
    featured: false,
    createdAt: "2026-07-01T00:00:00Z",
  },
  {
    id: "8",
    slug: "sustainable-city-loft",
    title: "Eco-Loft Sustainable City",
    location: "Sustainable City, Muscat",
    city: "Muscat",
    community: "Sustainable City",
    price: 220000,
    currency: "OMR",
    type: "Apartment",
    status: "Off-plan",
    bedrooms: 2,
    bathrooms: 2,
    area: 150,
    description: "Zero-carbon living with cutting-edge sustainable technology.",
    images: ["/p2.jpg", "/p3.jpg", "/p4.jpg"],
    amenities: [{ title: "Solar Panels", icon: "Sun" }, { title: "Smart Grid", icon: "Zap" }],
    paymentPlan: [{ percentage: "10%", condition: "Booking", timing: "Immediate" }],
    highlights: ["Eco-Friendly", "Smart City"],
    coordinates: { lat: 23.5500, lng: 58.4000 },
    featured: true,
    createdAt: "2026-08-01T00:00:00Z",
  },
  {
    id: "9",
    slug: "jebel-sifah-modern-villa",
    title: "Sifah Modern Villa",
    location: "Jebel Sifah, Muscat",
    city: "Muscat",
    community: "Jebel Sifah",
    price: 520000,
    currency: "OMR",
    type: "Villa",
    status: "Under Construction",
    bedrooms: 4,
    bathrooms: 3,
    area: 400,
    description: "Modern architecture blended with nature on the cliffs of Sifah.",
    images: ["/p4.jpg", "/p1.jpg", "/p2.jpg"],
    amenities: [{ title: "Infinity Pool", icon: "Waves" }, { title: "Garden", icon: "Tree" }],
    paymentPlan: [{ percentage: "30%", condition: "Down Payment", timing: "Immediate" }],
    highlights: ["Mountain Views", "Private Pool"],
    coordinates: { lat: 23.2100, lng: 58.3100 },
    featured: false,
    createdAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "10",
    slug: "muscat-bay-signature-villa",
    title: "Muscat Bay Signature Villa",
    location: "Muscat Bay, Muscat",
    city: "Muscat",
    community: "Muscat Bay",
    price: 3500000,
    currency: "OMR",
    type: "Villa",
    status: "For Sale",
    bedrooms: 8,
    bathrooms: 7,
    area: 1800,
    plotArea: 2200,
    description: "The pinnacle of luxury living in Oman, featuring unparalleled views and scale.",
    images: ["/p1.jpg", "/p2.jpg", "/p3.jpg", "/p4.jpg", "/p5.jpg"],
    amenities: [{ title: "Private Beach", icon: "Beach" }, { title: "Tennis Court", icon: "Trophy" }],
    paymentPlan: [{ percentage: "100%", condition: "Full Payment", timing: "At Closing" }],
    highlights: ["Extreme Luxury", "Signature Design"],
    coordinates: { lat: 23.4100, lng: 58.6100 },
    featured: true,
    createdAt: "2026-10-01T00:00:00Z",
  },
];
