import { PropertyUI } from "@/types/property";

export const MOCK_PROPERTIES: PropertyUI[] = [
  {
    id: "1",
    slug: "6br-alaya-villa-al-mouj",
    title: "6BR Alaya Villa",
    location: "Al Mouj Muscat, Muscat",
    city: "Muscat",
    community: "Al Mouj Muscat",
    price: 1406000,
    currency: "OMR",
    type: "Villa",
    status: "Available",
    bedrooms: 6,
    bathrooms: 5,
    area: 907.5,
    plotArea: 1005,
    description: "Welcome to a home where elegance meets everyday comfort. This stunning Alaya Villa in Al Mouj offers an unparalleled living experience with breathtaking waterfront views and world-class finishes. Designed for the most discerning investors, the property features expansive living areas, a private pool, and seamless integration of indoor and outdoor spaces.",
    images: [
      "/p1.jpg",
      "/p2.jpg",
      "/p3.jpg",
      "/p4.jpg",
      "/p5.jpg",
    ],
    amenities: [
      { title: "Private Beach", icon: "Beach" },
      { title: "Infinity Pool", icon: "Waves" },
      { title: "Smart Home", icon: "Cpu" },
      { title: "Private Elevator", icon: "ArrowUpCircle" },
      { title: "Garage", icon: "Car" },
      { title: "Gym", icon: "Dumbbell" },
      { title: "Marina Access", icon: "Ship" },
      { title: "Golf Course", icon: "Trophy" },
    ],
    paymentPlan: [
      { percentage: "5%", condition: "Down Payment", timing: "At Signing" },
      { percentage: "5%", condition: "Second Installment", timing: "After 3 Months" },
      { percentage: "15%", condition: "Installment 1", timing: "Month 6" },
      { percentage: "15%", condition: "Installment 2", timing: "Month 12" },
      { percentage: "60%", condition: "Final Payment", timing: "Handover 2026" },
    ],
    highlights: [
      "Freehold Ownership",
      "Foreign Investor Eligible",
      "Residency Benefits",
      "Lakefront Location",
      "Private Elevator",
      "Infinity Pool",
    ],
    coordinates: { lat: 23.6139, lng: 58.5233 },
    featured: true,
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "2",
    slug: "sultan-haitham-penthouse",
    title: "Sultan Haitham Penthouse",
    location: "Sultan Haitham City, Muscat",
    city: "Muscat",
    community: "Sultan Haitham City",
    price: 850000,
    currency: "OMR",
    type: "Penthouse",
    status: "Off Plan",
    bedrooms: 4,
    bathrooms: 4,
    area: 450,
    description: "An architectural masterpiece in the heart of the most ambitious urban project in Oman. This penthouse offers futuristic design, panoramic city views, and sustainable living at its finest.",
    images: [
      "/p2.jpg",
      "/p3.jpg",
      "/p1.jpg",
      "/p4.jpg",
    ],
    amenities: [
      { title: "Smart Systems", icon: "Zap" },
      { title: "Central Air", icon: "Wind" },
      { title: "Gym", icon: "Dumbbell" },
      { title: "Parks", icon: "TreePine" },
    ],
    paymentPlan: [
      { percentage: "10%", condition: "Booking", timing: "Immediate" },
      { percentage: "40%", condition: "During Construction", timing: "Quarterly" },
      { percentage: "50%", condition: "On Handover", timing: "2027" },
    ],
    highlights: [
      "Sustainable City",
      "Foreign Investor Eligible",
      "High ROI Potential",
      "Modern Infrastructure",
    ],
    coordinates: { lat: 23.5800, lng: 58.4500 },
    featured: true,
    createdAt: "2026-02-01T00:00:00Z",
  },
  {
    id: "3",
    slug: "bay-view-estate",
    title: "Bay View Estate",
    location: "Muscat Bay, Muscat",
    city: "Muscat",
    community: "Muscat Bay",
    price: 2100000,
    currency: "OMR",
    type: "Villa",
    status: "Available",
    bedrooms: 7,
    bathrooms: 6,
    area: 1200,
    plotArea: 1500,
    description: "A sanctuary of luxury nestled between the mountains and the turquoise waters of Muscat Bay. This estate defines opulence with its sweeping terraces and private beach access.",
    images: [
      "/p3.jpg",
      "/p4.jpg",
      "/p1.jpg",
      "/p2.jpg",
    ],
    amenities: [
      { title: "Private Beach", icon: "Palmtree" },
      { title: "Infinity Pool", icon: "Waves" },
      { title: "Wine Cellar", icon: "GlassWater" },
      { title: "Home Cinema", icon: "Film" },
    ],
    paymentPlan: [
      { percentage: "100%", condition: "Full Payment", timing: "At Closing" },
    ],
    highlights: [
      "Freehold Ownership",
      "Beachfront Location",
      "Extreme Privacy",
      "Mountain Views",
    ],
    coordinates: { lat: 23.4000, lng: 58.6000 },
    featured: true,
    createdAt: "2026-03-01T00:00:00Z",
  },
  {
    id: "4",
    slug: "sifah-cliff-house",
    title: "Sifah Cliff House",
    location: "Jebel Sifah, Muscat",
    city: "Muscat",
    community: "Jebel Sifah",
    price: 600000,
    currency: "OMR",
    type: "Villa",
    status: "Ready To Move",
    bedrooms: 3,
    bathrooms: 3,
    area: 350,
    description: "Experience the raw beauty of the Omani coast from this stunning cliffside residence. Perfect for those seeking peace and a direct connection with nature.",
    images: [
      "/p4.jpg",
      "/p1.jpg",
      "/p2.jpg",
      "/p3.jpg",
    ],
    amenities: [
      { title: "Outdoor Firepit", icon: "Flame" },
      { title: "Hiking Trails", icon: "Mountain" },
      { title: "Solar Power", icon: "Sun" },
    ],
    paymentPlan: [
      { percentage: "20%", condition: "Down Payment", timing: "At Signing" },
      { percentage: "80%", condition: "Bank Finance", timing: "At Transfer" },
    ],
    highlights: [
      "Ready To Move",
      "Cliffside View",
      "Eco-Friendly",
      "Quiet Neighborhood",
    ],
    coordinates: { lat: 23.2000, lng: 58.3000 },
    featured: false,
    createdAt: "2026-04-01T00:00:00Z",
  },
];
